<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Objetivo</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 50%;
            margin: 50px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }

        h2 {
            text-align: center;
        }

        form {
            width: 80%;
            margin: 0 auto;
        }

        label {
            font-weight: bold;
        }

        textarea {
            width: 100%;
            padding: 10px;
            margin-top: 5px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
            font-size: 16px;
            height: 100px;
        }

        input[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 15px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }

        input[type="submit"]:hover {
            background-color: #45a049;
        }
        
        .button {
            display: inline-block;
            padding: 15px 20px;
            background-color: #007bff;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s;
        }
        
        .button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>OBJETIVO PERSONAL</h2>
        
        <div class="container">
        <img class="car-image" src="" alt="OBJETIVO">
        <h2>OBJETIBO</h2>
        <p>Quiero ser un ingeniero de softawre con IA y especializarme en redes de seguridad cibernetica y como ultimo objetibo quiero policia y trabajar en el sistema de investigacion policial con todo lo aprendido en los años de estudio en la programacion con diferentes lenguajes eso es mi OBJETIVO</p>
        <P> ¡GRASIAS!</P>
      
    </div>

            <!-- Enlace al menú principal -->
            <a href="http://127.0.0.1:8000/menu" class="button">Volver al Menú Principal</a>
        </form>
    </div>
</body>
</html>
